[package]
name = "chat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.5.1"
serde = "1.0.204"
serde_json = "1.0.120"
env_logger = "0.11.3"
dotenv = "0.15.0"
lazy_static = "1.5.0"